server:
  port: 80
  servlet:
    context-path: /wechat

spring:
#------------------模板引擎 start--------------------
#模板引擎配置路径
  thymeleaf:
    cache: false #关闭缓存及时刷新
    mode: HTML5
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

